vallas_security:
    resource: "@VallasSecurityBundle/Resources/config/routing.yml"
    prefix:   /

e_social_admin:
    resource: "@ESocialAdminBundle/Resources/config/routing.yml"

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

