# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    fos_user.doctrine_registry:
        alias: doctrine

    kernel.listener.RequestListener:
            class: VallasSecurityBundle\EventListener\RequestListener
            tags:
                - { name: kernel.event_listener, event: kernel.controller, method: onFilterController }
                - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
            arguments: [@service_container, @security.context, @doctrine.orm.entity_manager, @router, @templating]

    vallas.doctrine.filter.configurator:
        class: AppBundle\Filter\Configurator
        arguments:
            - "@service_container"
            - "@doctrine.orm.entity_manager"
            - "@annotation_reader"
            - "@session"
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    vallas.security.permissions.checking:
        class: VallasSecurityBundle\Services\SecurityPermissionChecking
        arguments:
            - "@security.context"
            - "@doctrine.orm.entity_manager"
            - "@annotations.reader"
            - "@request_stack"